datasets:
  available: ["FEMNIST", "CIFAR10"]
  chosen: "FEMNIST"

optimizers:
  available: ["Adam", "Adagrad", "Adadelta", "RMSProp", "SGD"]
  chosen: "Adadelta"

classification:
  loss_functions:
    available: ["CrossEntropyLoss", "NLLLoss"]
    chosen: "CrossEntropyLoss"

wandb_tracking:
  activated: False

hyper-params:
  batch_size: 4
  learning_rate: 0.01
  num_epochs: 50
  num_workers: 2
