main:
  # available: FEMNIST, CIFAR10
  dataset: "CIFAR10"
client:
  hyper_params:
      learning_rate: 0.01
      num_epochs: 2
      batch_size: 32
server:
  num_rounds: 10
  # available: FedAvg, FedAdam, FedAvgM. FedYogi, FedAdagrad
  strategy: 'FedAvg'
  wandb_active: False
  wandb_key: "9b0f2332e55f68935986e18e23c302e0afbdf37b"
