task:
  available: ["classification", "regression"]
  chosen: "classification"
datasets:
  classification:
    available: ["FEMNIST", "CIFAR10", "IID"]
    chosen: "IID"
  regression:
    available: ["CaliforniaHousing"]
    chosen: "CaliforniaHousing"

optimizers:
  classification:
    available: ["Adam", "Adagrad", "Adadelta", "RMSProp", "SGD"]
    chosen: "Adam"
  regression:
    available: ["Adam"]
    chosen: "Adam"

loss_functions:
  classification:
    available: ["CrossEntropyLoss", "NLLLoss"]
    chosen: "CrossEntropyLoss"
  regression:
    available: ["MSELoss"]
    chosen: "MSELoss"

wandb:
  active_tracking: False
  login_key: <put key here>

hyper_params:
  batch_size: 10
  learning_rate: 0.001
  num_epochs: 50
  num_workers: 2
