dataset: CIFAR10 # [CIFAR10, FEMNIST]
n_epochs: 5
n_workers: 4
wandb:
  track: False
  # set api key from environment variable
  api_key: "key"
  entity: cs_team_b
  project: new_project
  group: new_group
max_clients: 10
show_plot: False
parallel_training: False
data_split_available: ["iid", "num_classes", "num_samples", "updated_non_iid"]
data_split_chosen: "iid"
visualize_data_split: False
data_split_config:
  dirichlet_alpha: 0.1
