main:
  # available: FEMNIST, CIFAR10
  dataset: "FEMNIST"
client:
  hyper_params:
      learning_rate: 0.0005
      num_epochs: 1
      batch_size: 64
server:
  num_rounds: 5
  # available: FedAvg, FedAdam, FedAvgM. FedYogi, FedAdagrad, CustomFedAvg
  strategy: 'FedAdam'
  wandb_active: False
  wandb_key: ""
