main:
  num_clients: 10

server:
  num_rounds: 3
  strategy: 'FedAvg'

client:
  hyper_params:
    learning_rate: 0.001
    num_epochs: 2
    batch_size: 32

defaults:
  - _self_
  - optional  custom: 'user_config'
