main:
  dataset: "FEMNIST"
client:
  hyper_params:
      learning_rate: 0.001
      num_epochs: 2
      batch_size: 32
server:
  num_rounds: 3
  strategy: 'FedAvg'
  wandb_active: False
  wandb_key: "<login key here>"
