num_clients: 4
data_split_available: ["iid", "num_classes", "num_samples", "updated_non_iid"]
data_split_config:
  dirichlet_alpha: 0.1
  niid_factor: 2
advanced_visualization: False
data_split_chosen: "iid"
wandb_active: False
wandb_key: "key"
