num_clients: 2
data_split_available: ["iid", "num_classes", "num_samples"]
data_split_config:
  dirichlet_alpha: 0.3
  niid_factor: 2
advanced_visualization: True
data_split_chosen: "num_samples"
wandb_active: False
wandb_key: "2858fc7a094d399980a53804e6e2208721f44609"
